config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "login", to: "sessions#new"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  root "buckets#index"

  namespace "recurrings" do
    resources :insights, only: [ :index ]
  end

  resources :recurrings
  resources :buckets
  resources :transactions
  resources :limits, only: [ :new, :create, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recurring.rb
class Recurring < ApplicationRecord
  belongs_to :user, optional: false

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :day_of_month, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 31 }

  def self.total_over_time
    group(:day_of_month)
      .sum(:amount)
      .sort
      .each_with_object({}) do |(day, amount), object|
      object[day_to_date(day)] = amount + (object.values.last || 0)
    end
  end

  def self.amount_by_day
    group(:day_of_month)
      .sum(:amount)
      .sort
      .each_with_object({}) do |(day, amount), object|
      object[day_to_date(day)] = amount
    end
  end

  def due_date
    Date.current.change(day: day_of_month.clamp(1, Date.current.end_of_month.day))
  end

  def self.day_to_date(day)
    Date.current.change(day: day.clamp(1, Date.current.end_of_month.day))
  end
end

app/controllers/recurrings/insights_controller.rb
class Recurrings::InsightsController < ApplicationController
  before_action :set_recurrings

  def index
  end

  private

    def set_recurrings
      @recurrings = Recurring.all
    end
end

app/controllers/recurrings_controller.rb
class RecurringsController < ApplicationController
  before_action :set_recurring, only: [ :show, :edit, :update, :destroy ]

  def index
    @recurrings = Current.user.recurrings.all
  end

  def show
  end

  def new
    @recurring = Current.user.recurrings.new
  end

  def create
    @recurring = Current.user.recurrings.new(recurring_params)

    if @recurring.save
      redirect_to recurrings_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @recurring.update(recurring_params)
      redirect_to recurrings_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recurring.destroy

    redirect_to recurrings_url
  end

  private

    def recurring_params
      params.expect(recurring: [ :name, :amount, :day_of_month, :link ])
    end

    def set_recurring
      @recurring = Current.user.recurrings.find(params[:id])
    end
end

app/helpers/recurrings/insights_helper.rb
module Recurrings::InsightsHelper
end

app/helpers/recurrings_helper.rb
module RecurringsHelper
  def day_to_month(day)
    Date.current.change(day: day.clamp(1, Date.current.end_of_month.day))
  end
  def cost_over_time
    @recurrings_grouped ||= @recurrings.group(:day_of_month).sum(:amount).sort

    @recurrings_grouped.each_with_object({}) do |(day, amount), object|
      object[day_to_month(day)] = amount
    end
  end

  def total_over_time
    @recurrings_grouped ||= @recurrings.group(:day_of_month).sum(:amount).sort

    @recurrings_grouped.each_with_object({}) do |(day, amount), object|
      object[day_to_month(day)] = amount + (object.values.last || 0)
    end
  end
end

# @recurrings.group_by(&:day_of_month).transform_values do |recurrings|
#   recurrings.sum(&:amount)
# end

# running_total = 0
# daily_totals.sort.each do |day, amount|
#   running_total += amount
#   [ day, running_total ]
# end

app/views/recurrings/_form.html.erb
<%= form_with model: recurring do |form| %>
  <div class="recurring__form-container">
    <div class="form__input-container">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <%= error_for recurring, :name %>
    </div>
    <div class="form__input-container">
      <%= form.label :amount %>
      <%= form.text_field :amount %>
      <%= error_for recurring, :amount %>
    </div>
    <div class="form__input-container">
      <%= form.label :day_of_month %>
      <%= form.number_field :day_of_month %>
      <%= error_for recurring, :day_of_month %>
    </div>
    <div class="form__input-container">
      <%= form.label :link %>
      <%= form.text_field :link %>
      <%= error_for recurring, :link %>
    </div>
  </div>
  <div class="form__action-container">
    <%= form.submit class: "btn btn--primary" %>
    <%= link_to "Cancel", recurrings_path, class: "btn" %>
    <% if recurring.persisted? %>
      <label for="<%= dom_id recurring, :destroy %>" class="btn btn--destroy" tabindex="0">Destroy</label>
    <% end %>
  </div>
<% end %>

app/views/recurrings/edit.html.erb
<div class="page-header">
  <div class="page-header__controls">
    <%= render 'partials/back', path: recurrings_path %>
  </div>
</div>

<section>
  <div class="detailed-card">
    <div class="detailed-card__header">
      <h3>Edit <%= @recurring.name %></h3>
    </div>
    <div class="detailed-card__inner">
      <%= render 'recurrings/form', recurring: @recurring %>

      <div class="external-destroy">
        <%= button_to "Destroy", recurring_path(@recurring), method: :delete, class: "", id: dom_id(@recurring, :destroy) %>
      </div>
    </div>
  </div>
</section>

app/views/recurrings/index.html.erb
<div class="page-header">
  <div class="page-header__totals-container">
    <div class="page-header__total">
      <p>Total</p>
      <p><%= number_to_currency @recurrings.sum(&:amount) %></p>
    </div>
  </div>

  <div class="page-header__controls">
    <%= render 'partials/back', path: buckets_path %>
    <%= render "partials/round_link", path: recurrings_insights_path, details: "Insights", sr_text: "View insights" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chart-spline">
        <path d="M3 3v16a2 2 0 0 0 2 2h16"/>
        <path d="M7 16c.5-2 1.5-7 4-7 2 0 2 3 4 3 2.5 0 4.5-5 5-7"/>
      </svg>
    <% end %>
    <%= render "partials/round_link", path: new_recurring_path, details: "New recurring", sr_text: "New recurring cost", primary: true do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-calendar-plus">
        <path d="M8 2v4"/>
        <path d="M16 2v4"/>
        <path d="M21 13V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8"/>
        <path d="M3 10h18"/>
        <path d="M16 19h6"/>
        <path d="M19 16v6"/>
      </svg>
    <% end %>
  </div>
</div>

<ul class="recurring__list">
  <li class="empty-state">
    Nothing here
  </li>
  <% @recurrings.each do |recurring| %>
    <li class="card">
      <div>
        <div class="card__header">
          <h3>
            <%= recurring.name %>
          </h3>
          <%= link_to edit_recurring_path(recurring) do %>
            <span class="sr-only">Edit reccuring for <%= recurring.name %></span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil-line">
              <path d="M12 20h9"/>
              <path d="M16.376 3.622a1 1 0 0 1 3.002 3.002L7.368 18.635a2 2 0 0 1-.855.506l-2.872.838a.5.5 0 0 1-.62-.62l.838-2.872a2 2 0 0 1 .506-.854z"/>
              <path d="m15 5 3 3"/>
            </svg>
          <% end %>
        </div>
        <div class="card__detail">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-dollar-sign">
            <circle cx="12" cy="12" r="10"/>
            <path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/>
            <path d="M12 18V6"/>
          </svg>
          <%= number_to_currency recurring.amount %>
        </div>
        <div class="card__detail">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-calendar-days">
            <path d="M8 2v4"/>
            <path d="M16 2v4"/>
            <rect width="18" height="18" x="3" y="4" rx="2"/>
            <path d="M3 10h18"/>
            <path d="M8 14h.01"/>
            <path d="M12 14h.01"/>
            <path d="M16 14h.01"/>
            <path d="M8 18h.01"/>
            <path d="M12 18h.01"/>
            <path d="M16 18h.01"/>
          </svg>
          <%= recurring.due_date.strftime('%B %e, %Y') %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/recurrings/new.html.erb
<div class="page-header">
  <div class="page-header__controls">
    <%= render 'partials/back', path: recurrings_path %>
  </div>
</div>

<section>
  <div class="detailed-card">
    <div class="detailed-card__header">
      <h3>New recurring</h3>
    </div>
    <div class="detailed-card__inner">
      <%= render 'recurrings/form', recurring: @recurring %>
    </div>
  </div>
</section>

app/views/recurrings/show.html.erb
Why is this showing?