config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "login", to: "sessions#new"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  root "buckets#index"

  namespace "recurrings" do
    resources :insights, only: [ :index ]
  end

  resources :recurrings
  resources :buckets
  resources :transactions
  resources :limits, only: [ :new, :create, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  belongs_to :user, optional: false
  has_many :transactions, -> { order(date: :desc, id: :desc) }
  has_many :current_month_transactions, -> { current_month.order(date: :desc, id: :desc) }, class_name: "Transaction"
  # has_many :transactions_by_month, ->(month) { by_month(month).order(date: :desc, id: :desc) }, class_name: "Transaction"

  validates :name, presence: true
  validates :limit, numericality: { greater_than: 0 }, allow_blank: true
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [ :show, :edit, :update, :destroy ]

  def index
    @buckets = Current.user.buckets.includes(:current_month_transactions).all
    # @transactions = Current.user.transactions.includes(:bucket).by_month(Date.current).ordered_by_date
  end

  def show
  end

  def new
    @bucket = Current.user.buckets.new
  end

  def create
    @bucket = Current.user.buckets.new(bucket_params)

    if @bucket.save
      respond_to do |format|
        format.html { redirect_to buckets_url }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bucket.update(bucket_params)
      redirect_to buckets_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bucket.destroy

    redirect_to buckets_url
  end

  private

    def bucket_params
      params.expect(bucket: [ :name, :limit ])
    end

    def set_bucket
      @bucket = Current.user.buckets.find(params[:id])
    end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_bucket.html.erb
<%# locals: (bucket:) %>

<li class="detailed-card">
  <div class="detailed-card__header">
    <h3><%= bucket.name %></h3>
    <div class="detailed-card__actions">
      <div class="bucket-card__controls">
        <%= link_to edit_bucket_path(bucket), class: 'bucket-card__edit' do %>
          <span class="sr-only">Edit bucket for <%= bucket.name %></span>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-pencil-line">
            <path d="M12 20h9"/>
            <path d="M16.376 3.622a1 1 0 0 1 3.002 3.002L7.368 18.635a2 2 0 0 1-.855.506l-2.872.838a.5.5 0 0 1-.62-.62l.838-2.872a2 2 0 0 1 .506-.854z"/>
            <path d="m15 5 3 3"/>
          </svg>
        <% end %>
        <%= link_to new_transaction_path(bucket_id: bucket.id), class: 'bucket-card__new-transaction' do %>
          <span class="sr-only">Add transaction</span>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus">
            <path d="M5 12h14"/>
            <path d="M12 5v14"/>
          </svg>
        <% end %>
      </div>
    </div>
  </div>
  <div class="detailed-card__inner">
    <%#= turbo_frame_tag dom_id(bucket, "new_transaction"), class: "transaction__new" %>
    <ul class="bucket__transaction-list" id="<%= dom_id(bucket, "transaction_list") %>">
      <%= render partial: "buckets/transaction", collection: bucket.current_month_transactions %>
      <li class="empty-state">
        No transactions
      </li>
    </ul>
  </div>
  <div class="detailed-card__footer">
    <div class="bucket__card-limit-container">
      <!-- Add the styling for this to the bucket specific file. this isn't universal-->

      <%= tag.div id: dom_id(bucket, "transaction_total",), class: "bucket-card__limit" do %>
        <%= render "buckets/bucket_total", bucket: bucket %>
      <% end %>
      <% if bucket.limit.present? %>
        <span class="bucket-card__limit"> / <%= number_to_currency(bucket.limit) %></span>
      <% end %>
    </div>
  </div>
</li>

app/views/buckets/_bucket_total.html.erb
<%# locals: (bucket:) %>

<% sum = bucket.current_month_transactions.sum(&:amount) %>
<span class="<%= sum > 100 ? 'red' : '' %>"><%= number_to_currency(sum) %></span>

app/views/buckets/_form.html.erb
<%= form_with model: bucket do |form| %>
  <div class="bucket__form-container">
    <div class="form__input-container">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <%= error_for bucket, :name %>
    </div>
    <div class="form__input-container">
      <%= form.label :limit %>
      <%= form.text_field :limit %>
      <%= error_for bucket, :limit %>
    </div>
  </div>
  <div class="form__action-container">
    <%= form.submit class: "btn btn--primary" %>
    <%= link_to "Cancel", buckets_path, class: "btn" %>
    <% if bucket.persisted? %>
      <label for="<%= dom_id bucket, :destroy %>" class="btn btn--destroy" tabindex="0">Destroy</label>
    <% end %>
  </div>
<% end %>

app/views/buckets/_total.html.erb
<p>Total</p>
<!--
<p><%#= number_to_currency @buckets.sum { |bucket| bucket.transactions.sum(&:amount) } %></p>-->
<p><%= number_to_currency Current.user.current_month_transactions.sum(:amount) %></p>

app/views/buckets/_transaction.html.erb
<%# locals: (transaction:) %>

<li class="bucket__transaction">
  <div class="bucket__transaction-date">
    <%= transaction.date.strftime('%b %e, %Y') %>
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dot">
    <circle cx="12.1" cy="12.1" r="1"/>
  </svg>
  <div class="bucket__transaction-name">
    <%= transaction.name %>
  </div>
  <div class="bucket__transaction-amount">
    <%= number_to_currency transaction.amount %>
  </div>
</li>

app/views/buckets/create.turbo_stream.erb
<%= turbo_stream.before "bucket-empty-state", @bucket %>

<%= turbo_stream.update Bucket.new, "" %>

<%#= turbo_stream.update "transaction-total" do %>
  <%#= render "buckets/total" %>
<%# end %>

app/views/buckets/edit.html.erb
<div class="page-header">
  <div class="page-header__controls">
    <%= render 'partials/back', path: buckets_path %>
  </div>
</div>

<section>
  <div class="detailed-card">
    <div class="detailed-card__header">
      <h3>Edit bucket</h3>
    </div>
    <div class="detailed-card__inner">
      <%= render 'buckets/form', bucket: @bucket %>

      <div class="external-destroy">
        <%= button_to "Destroy", bucket_path(@bucket), method: :delete, class: "", id: dom_id(@bucket, :destroy) %>
      </div>
    </div>
  </div>
</section>

app/views/buckets/index.html.erb
<div class="page-header">
  <div class="page-header__totals-container">
    <%= turbo_frame_tag "transaction-total", class: "page-header__total" do %>
      <%= render "buckets/total" %>
    <% end %>
    <div class="page-header__total">
      <% limit = Current.user.limits.last %>
      <% if limit %>
        <p><%= link_to "Limit", edit_limit_path(limit) %></p>
      <% else %>
        <p>Limit</p>
      <% end %>
      <% if limit %>
        <p><%= number_to_currency(limit.amount) %>
        </p>
      <% else %>
        <%= link_to "Not set", new_limit_path %>
      <% end %>
    </div>
  </div>

  <div class="page-header__controls">
    <div class="flex-expand"></div>
    <%= render "partials/round_link", path: recurrings_path, details: "Recurring", sr_text: "Recurring costs" do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="lucide lucide-calendar-clock"
      >
        <path d="M21 7.5V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.5"/>
        <path d="M16 2v4"/>
        <path d="M8 2v4"/>
        <path d="M3 10h5"/>
        <path d="M17.5 17.5 16 16.3V14"/>
        <circle cx="16" cy="16" r="6"/>
      </svg>
    <% end %>
    <%= render "partials/round_link", path: new_bucket_path, details: "New bucket", sr_text: "New bucket", primary: true, data: { turbo_frame: dom_id(Bucket.new) } do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="lucide lucide-folder-plus"
      >
        <path d="M12 10v6"/>
        <path d="M9 13h6"/>
        <path
          d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"
        />
      </svg>
    <% end %>
  </div>
</div>

<%= turbo_frame_tag Bucket.new, class: "bucket__new" %>

<ul class="bucket__list">
  <%= render @buckets %>
  <li class="empty-state" id="bucket-empty-state">
    Nothing here
  </li>
</ul>

app/views/buckets/new.html.erb
<div class="page-header">
  <div class="page-header__controls">
    <%= render 'partials/back', path: buckets_path %>
  </div>
</div>

<%= turbo_frame_tag @bucket do %>
  <section>
    <div class="detailed-card">
      <div class="detailed-card__header">
        <h3>New bucket</h3>
      </div>
      <div class="detailed-card__inner">
        <%= render 'buckets/form', bucket: @bucket %>
      </div>
    </div>
  </section>
<% end %>