config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  get "login", to: "sessions#new"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  root "buckets#index"

  namespace "recurrings" do
    resources :insights, only: [ :index ]
  end

  resources :recurrings
  resources :buckets
  resources :transactions
  resources :limits, only: [ :new, :create, :edit, :update ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Budget" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <!--
    <link rel="icon" href="/icon.png" type="image/png">--> <!--
    <link rel="icon" href="/icon.svg" type="image/svg+xml">--> <!--
    <link rel="apple-touch-icon" href="/icon.png">-->
    <link rel="icon" href="/favicon.ico" sizes="any">
    <!--
    <link rel="icon" href="/icon-192.png" type="image/png">-->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <!--
    <meta name="theme-color" content="black" media="(prefers-color-scheme: dark)">
    -->
    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= yield :page_specific %>
  </head>

  <body>
    <header
      class="container"
      <%#data-controller="header"%>
      <%#data-action="scroll@document->header#log:passive"%>
    >
      <div data-header-target="container">
        <%= link_to buckets_path do %>
          <%= image_tag "/logo.webp", height: 32, width: 32, class: "header__image" %>
          <h1>Budget<span>Fast</span></h1>
        <% end %>
      </div>
    </header>
    <main class="container">
      <%= render "partials/hero" %>

      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <p><%= Current.user.email_address %></p>
        <%= button_to "Logout", session_path, method: :delete, class: "btn" %>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/guest.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Budget" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <!--  <meta name="theme-color" content="black" media="(prefers-color-scheme: dark)">-->

  <%# Includes all stylesheet files in app/views/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= yield :page_specific %>
</head>

<body>
<header class="container">
  <%= link_to buckets_path do %>
    <%= image_tag "/icon-192.png", height: 32, width: 32, class: "header__image" %>
    <h1>Budget<span>Fast</span></h1>
  <% end %>
</header>
<main class="container">
  <%= yield %>
</main>
</body>
</html>